name = "Sedlex"
uuid = "64ae60aa-b9fb-4c04-ad91-ac2211b2e73c"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
